- name: Copy mongodb repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: etc/yum.repos.d/mongodb.repo

- name: Install mongodb
  ansible.builtin.dnf:
    name: mongodb-org
    state: present

- name: update mongodb listen address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'


- name: System service started
  ansible.builtin.systemd_service:
    name: mongod
    state: restarted
    enabled: yes
#print_heading "system service started"
#service_no_daemon
#status_check $?