- name: set-prompt
  ansible.builtin.shell: set-prompt {{ app_name }}-{{ env }}

- name: load maven
  ansible.builtin.include_role:
    name: common
    tasks_from: maven

- name: install MYSQL Client
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name: Load SQL File
  ansible.builtin.shell: mysql -h mysql-{{ env }}.devops24.shop -uroot -pRoboShop@1 < /app/db/{{ item }}.sql
  loop:
    - schema
    - app-user
    - master-data
#password is hard coded

- name: Restart Shipping
  ansible.builtin.systemd_service:
    name: shipping
    state: restarted