- name: Demo on variables
  hosts: localhost
  connection: local #to test in local we use the keyword connection: local
  vars:
    URL: vars.google.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}