- name: set-prompt
  ansible.builtin.shell: set-prompt {{ app_name }}-{{ env }}

- name: install mysql server
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: start mysql services
  ansible.builtin.systemd_service:
    name: mysqld
    enabled: yes
    state: restarted

- name: setup mysql password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1
  # password is hard coded. need to change