

- name: Copy Dispatch Service
  ansible.builtin.templates:
    src: dispatch.service
    dest: /etc/systemd/system/dispatch.service

- name: load golang setup
  ansible.builtin.include_role:
    name: common
    tasks_from: golang
