- name: Set prompt
  ansible.builtin.shell: set-prompt{{ app_name }}-{{ env }}

- name: Copy Dispatch Service
  ansible.builtin.template:
    src: dispatch.service
    dest: /etc/systemd/system/dispatch.service

- name: load golang setup
  ansible.builtin.include_role:
    name: common
    tasks_from: golang
