- name: Set prompt
  ansible.builtin.shell: set-prompt {{ app_name }}-{{ env }}

#  nodejs_setup
#
#  print_heading "Install mongodb client"
#  dnf install mongodb-mongosh -y &>>$log_file
#  status_check $?
#
#  print_heading "load master data"
#  mongosh --host mongodb.devops24.shop </app/db/master-data.js &>>$log_file
#  status_check $?
#
#  print_heading "Restart catalogue service"
#  systemctl restart $app_name &>>$log_file
#  status_check $?

- name: load nodejs
  ansible.builtin.include_role:
    name: common
    file: nodejs

