
#print_heading "Download application dependencies"
#go mod init dispatch &>>$log_file
#go get &>>$log_file
#go build &>>$log_file
#echo $?
#
#print_heading "Start system service"
#service_start
#echo $?

- name: install Golang
  ansible.builtin.dnf:
    name: golang
    state: installed

- name: load app prerequisites
  ansible.builtin.include_tasks:
    name: app_prerequisites

- name: Download application dependencies
  ansible.builtin.shell: "{{ item }}"
  loop:
    - go mod init dispatch
    - go get
    - go build

- name: Start System Service
  ansible.builtin.systemd_service:
    name: golang
    daemon-reload: yes
    enabled: yes
    state: restarted

