- name: install Golang
  ansible.builtin.dnf:
    name: golang
    state: installed

- name: load app prerequisites
  ansible.builtin.include_tasks:
    file: app_prerequisites.yml

- name: Download application dependencies
  ansible.builtin.shell: "{{ item }}"
  dir: /app
  loop:
    - go mod init dispatch
    - go get
    - go build

- name: Start System Service
  ansible.builtin.systemd_service:
    name: golang
    daemon-reload: yes
    enabled: yes
    state: restarted