- name: copy the service file
  ansible.builtin.template:
    src: "{{ app_name }}.service"
    dest: /etc/systemd/system/{{ app_name }}.service

- name: system service started
  ansible.builtin.systemd_service:
    name: "{{ app_name }}"
    state: restarted
    enabled: yes
    daemon-reload: yes